# Netlify Configuration File

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 404

[[redirects]]
  from = "/*.apk"
  to = "/:splat.apk"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all, index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"

[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "all, index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
